# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ‘10.0’

target 'XW_Customs_Ios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  #pod 'iOS-Echarts'
  # Pods for XW_Object
  pod 'AFNetworking','3.2.1'
  
  pod 'SDWebImage'
  
#  pod 'MBProgressHUD'
  
#  pod 'DateTools'

  pod 'MBProgressHUD'
  
  pod 'Masonry'
  
  pod 'MJRefresh'
  
#  pod 'MJExtension'
  pod 'MJExtension', '3.1.2'
  
  pod 'SDAutoLayout', '~> 2.1.3'
  
#  pod 'MyLayout'
  
#  pod 'ReactiveCocoa'
  pod 'ReactiveObjC'
  
  pod 'JPFPSStatus', '~> 0.1'
  
  pod 'JLRoutes'
  
  #pod 'JXCategoryView'
  pod 'JXCategoryView', '~> 1.5.4'
  
  pod 'JXPagingView/Pager'
  
  pod 'UITableView+FDTemplateLayoutCell'
  
  pod 'WebViewJavascriptBridge', '~> 6.0'
  
  pod 'PAPreferences'
  #开屏广告、启动广告解决方案-支持静态/动态图片广告/mp4视频广告
  pod 'XHLaunchAd', '~> 3.9.8'
  #子类化UIButton实现IOS倒计时按钮,常常用于注册等发送验证码的时候进行倒计时操作
  #pod 'JKCountDownButton'
  
  pod 'IQKeyboardManager'
  # 功能最多样式最多的弹窗，支持自定义视图,链式编程调用
  pod 'WMZDialog'
  
  #友盟推送
  pod 'UMCommon'    #//必须集成
  pod 'UMDevice'    #//必须集成

  #//pod <友盟+SDK名> 按需复制相应SDK名称代码

  #//依赖库

  pod 'UMCCommonLog'  #//可选，日志插件

  pod 'UMAPM'   #//必选，APM组件，原错误分析升级为独立产品U-APM

  pod 'UMPush'  #//必选，推送组件，由原来的UMCPush变为UMPush

  pod 'UMLink'         #//必选，智能超链组件
  
  
  
  pod 'JJCollectionViewRoundFlowLayout'
  
  pod 'STAlertView'
  #微信支付
#  pod 'WechatOpenSDK', '~> 1.8.7'
  #支付宝支付
  #pod 'AlipaySDK-iOS'
  
  # AlipaySDK-iOS与UMCSecurityPlugins的UTDID冲突的解决方案
#  pod 'AlipaySDK_No_UTDID'
#  pod 'AlipaySDK_No_UTDID_SUN', '~> 15.2.0'
  
  #pod 'mob_linksdk_pro'
  
  pod 'XKEmptyPlaceView'
  
#  pod 'TTTAttributedLabel'
  
  #Lottie 动画过程
  pod 'lottie-ios'
  
  pod 'ZKCycleScrollView'
  
  #TradPlus聚合平台
  #pod 'TradPlusSDK', '5.4.6'
  #pod 'TradPlusSDK/GDTMobAdapter', '5.4.6'
  #pod 'GDTMobSDK', '4.12.1'
end
